// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXT0JifknAIsnvXGgInx1UMVFvY8H8lc4',
    appId: '1:272895591777:web:8a023f20b76b013c10f120',
    messagingSenderId: '272895591777',
    projectId: 'bookverse-92589',
    authDomain: 'bookverse-92589.firebaseapp.com',
    storageBucket: 'bookverse-92589.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6c7AAQJem2FUIrEMoxgkk5xJVMQOZsX8',
    appId: '1:272895591777:android:e3afe7f505e3cfaa10f120',
    messagingSenderId: '272895591777',
    projectId: 'bookverse-92589',
    storageBucket: 'bookverse-92589.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXT0JifknAIsnvXGgInx1UMVFvY8H8lc4',
    appId: '1:272895591777:web:d3a7e2ee9b2a9ba910f120',
    messagingSenderId: '272895591777',
    projectId: 'bookverse-92589',
    authDomain: 'bookverse-92589.firebaseapp.com',
    storageBucket: 'bookverse-92589.firebasestorage.app',
  );
}
